# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='slug',
            field=models.SlugField(default='invalid_slug'),
            preserve_default=False,
        ),
    ]
