# Generated by Django 2.2.1 on 2019-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcoursupuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
