# Generated by Django 2.2.1 on 2019-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0002_auto_20190519_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcoursupmessagereculog',
            name='payload',
            field=models.BinaryField(blank=True, verbose_name='données reçues'),
        ),
        migrations.AlterField(
            model_name='action',
            name='categorie',
            field=models.SmallIntegerField(choices=[(0, "Envoi du dossier d'inscription"), (1, "Envoi du dossier pour l'internat"), (2, 'Inscription administrative'), (3, 'Demande de pièces complémentaires'), (4, "Enregistrement d'une démission"), (5, 'Traiter la demande de césure')], verbose_name='catégorie'),
        ),
    ]
