# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0002_classe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
