# Generated by Django 2.2.1 on 2019-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0003_auto_20190528_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcoursupmessagereculog',
            name='payload',
            field=models.BinaryField(blank=True, default=b'', verbose_name='données reçues'),
        ),
    ]
