# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0003_auto_20180520_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
