# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0004_auto_20180521_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name': 'étudiant'},
        ),
    ]
