# Generated by Django 2.2.1 on 2019-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0004_auto_20190528_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcoursupmessagereculog',
            name='payload',
            field=models.BinaryField(blank=True, default=b'', null=True, verbose_name='données reçues'),
        ),
    ]
