# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0005_auto_20180521_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposition',
            options={'get_latest_by': 'date_proposition'},
        ),
        migrations.AddField(
            model_name='action',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='proposition_actuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='parcoursup.Proposition'),
        ),
        migrations.AlterField(
            model_name='action',
            name='statut',
            field=models.SmallIntegerField(choices=[(0, 'À traiter'), (1, 'Fait'), (2, 'Rien à faire')], default=0),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='remplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacee_par', to='parcoursup.Proposition'),
        ),
    ]
