# Generated by Django 2.2.1 on 2019-06-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0006_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcoursupsynchro',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'extraction web'), (2, 'interface synchrone')], default=1, verbose_name='source des données'),
            preserve_default=False,
        ),
    ]
