# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0007_auto_20180522_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='statut',
            field=models.SmallIntegerField(choices=[(0, 'À traiter'), (1, 'Fait'), (2, 'Rien à faire'), (3, 'Annulée')], default=0),
        ),
    ]
