# Generated by Django 2.2.1 on 2019-06-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0007_parcoursupsynchro_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code_parcoursup',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
