# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0008_auto_20180522_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='code_parcoursup',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
