# Generated by Django 2.2.1 on 2019-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0008_etudiant_codepsup_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='inscription',
            field=models.BooleanField(default=False, verbose_name='inscription réalisée'),
        ),
    ]
