# Generated by Django 2.2.1 on 2019-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0009_inscription_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='ine',
            field=models.CharField(blank=True, null=True, max_length=11, unique=True, verbose_name="INE (numéro d'étudiant)"),
        ),
    ]
