# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0012_auto_20180526_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='capacite',
            field=models.SmallIntegerField(default=0, verbose_name='capacité'),
            preserve_default=False,
        ),
    ]
