# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0013_classe_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='surbooking',
            field=models.SmallIntegerField(default=0),
        ),
    ]
