# Generated by Django 2.0.5 on 2018-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0014_classe_surbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'M.'), (2, 'Mme')], null=True),
        ),
    ]
