# Generated by Django 2.0.5 on 2018-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0015_etudiant_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcoursupSynchro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='début')),
                ('date_fin', models.DateTimeField(verbose_name='fin')),
                ('mode', models.SmallIntegerField(choices=[(1, 'Automatique'), (2, 'Manuelle')])),
                ('resultat', models.SmallIntegerField(blank=True, choices=[(1, 'Réussie'), (2, 'Échec')], null=True, verbose_name='résultat')),
            ],
        ),
    ]
