# Generated by Django 2.0.6 on 2018-07-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0016_parcoursupsynchro'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
    ]
