# Generated by Django 2.0.6 on 2018-07-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcoursup', '0017_etudiant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='telephone_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone mobile'),
        ),
    ]
